// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/XRay-Addons/xrayman/node/pkg/api/http/gen (interfaces: SecurityHandler)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_security_handler.go -package=mocks github.com/XRay-Addons/xrayman/node/pkg/api/http/gen SecurityHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityHandler is a mock of SecurityHandler interface.
type MockSecurityHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityHandlerMockRecorder
	isgomock struct{}
}

// MockSecurityHandlerMockRecorder is the mock recorder for MockSecurityHandler.
type MockSecurityHandlerMockRecorder struct {
	mock *MockSecurityHandler
}

// NewMockSecurityHandler creates a new mock instance.
func NewMockSecurityHandler(ctrl *gomock.Controller) *MockSecurityHandler {
	mock := &MockSecurityHandler{ctrl: ctrl}
	mock.recorder = &MockSecurityHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityHandler) EXPECT() *MockSecurityHandlerMockRecorder {
	return m.recorder
}

// HandleBearerAuth mocks base method.
func (m *MockSecurityHandler) HandleBearerAuth(ctx context.Context, operationName string, t api.BearerAuth) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBearerAuth", ctx, operationName, t)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBearerAuth indicates an expected call of HandleBearerAuth.
func (mr *MockSecurityHandlerMockRecorder) HandleBearerAuth(ctx, operationName, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBearerAuth", reflect.TypeOf((*MockSecurityHandler)(nil).HandleBearerAuth), ctx, operationName, t)
}
