// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/XRay-Addons/xrayman/nodesync/pkg/api/http/gen (interfaces: SecuritySource)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_security_source.go -package=mocks github.com/XRay-Addons/xrayman/nodesync/pkg/api/http/gen SecuritySource
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockSecuritySource is a mock of SecuritySource interface.
type MockSecuritySource struct {
	ctrl     *gomock.Controller
	recorder *MockSecuritySourceMockRecorder
	isgomock struct{}
}

// MockSecuritySourceMockRecorder is the mock recorder for MockSecuritySource.
type MockSecuritySourceMockRecorder struct {
	mock *MockSecuritySource
}

// NewMockSecuritySource creates a new mock instance.
func NewMockSecuritySource(ctrl *gomock.Controller) *MockSecuritySource {
	mock := &MockSecuritySource{ctrl: ctrl}
	mock.recorder = &MockSecuritySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecuritySource) EXPECT() *MockSecuritySourceMockRecorder {
	return m.recorder
}

// BearerAuth mocks base method.
func (m *MockSecuritySource) BearerAuth(ctx context.Context, operationName string) (api.BearerAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BearerAuth", ctx, operationName)
	ret0, _ := ret[0].(api.BearerAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BearerAuth indicates an expected call of BearerAuth.
func (mr *MockSecuritySourceMockRecorder) BearerAuth(ctx, operationName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BearerAuth", reflect.TypeOf((*MockSecuritySource)(nil).BearerAuth), ctx, operationName)
}
