// Code generated by ogen, DO NOT EDIT.

package ogenclient

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/ClientConfigTemplate
type ClientConfigTemplate struct {
	Template        []ClientConfigTemplateItem `json:"template"`
	VlessEmailField string                     `json:"vlessEmailField"`
	VlessUUIDField  string                     `json:"vlessUUIDField"`
}

// GetTemplate returns the value of Template.
func (s *ClientConfigTemplate) GetTemplate() []ClientConfigTemplateItem {
	return s.Template
}

// GetVlessEmailField returns the value of VlessEmailField.
func (s *ClientConfigTemplate) GetVlessEmailField() string {
	return s.VlessEmailField
}

// GetVlessUUIDField returns the value of VlessUUIDField.
func (s *ClientConfigTemplate) GetVlessUUIDField() string {
	return s.VlessUUIDField
}

// SetTemplate sets the value of Template.
func (s *ClientConfigTemplate) SetTemplate(val []ClientConfigTemplateItem) {
	s.Template = val
}

// SetVlessEmailField sets the value of VlessEmailField.
func (s *ClientConfigTemplate) SetVlessEmailField(val string) {
	s.VlessEmailField = val
}

// SetVlessUUIDField sets the value of VlessUUIDField.
func (s *ClientConfigTemplate) SetVlessUUIDField(val string) {
	s.VlessUUIDField = val
}

type ClientConfigTemplateItem jx.Raw

// EditUsersOK is response for EditUsers operation.
type EditUsersOK struct{}

// Ref: #/EditUsersRequest
type EditUsersRequest struct {
	Add    []User `json:"add"`
	Remove []User `json:"remove"`
}

// GetAdd returns the value of Add.
func (s *EditUsersRequest) GetAdd() []User {
	return s.Add
}

// GetRemove returns the value of Remove.
func (s *EditUsersRequest) GetRemove() []User {
	return s.Remove
}

// SetAdd sets the value of Add.
func (s *EditUsersRequest) SetAdd(val []User) {
	s.Add = val
}

// SetRemove sets the value of Remove.
func (s *EditUsersRequest) SetRemove(val []User) {
	s.Remove = val
}

// Ref: #/Error
type Error struct {
	Message string       `json:"Message"`
	Details OptNilString `json:"Details"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() OptNilString {
	return s.Details
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val OptNilString) {
	s.Details = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Node performance.
// Ref: #/Performance
type Performance struct {
	CpuLoad         float32 `json:"CpuLoad"`
	RamLoad         float32 `json:"RamLoad"`
	MemLoad         float32 `json:"MemLoad"`
	OpenConnections int32   `json:"OpenConnections"`
}

// GetCpuLoad returns the value of CpuLoad.
func (s *Performance) GetCpuLoad() float32 {
	return s.CpuLoad
}

// GetRamLoad returns the value of RamLoad.
func (s *Performance) GetRamLoad() float32 {
	return s.RamLoad
}

// GetMemLoad returns the value of MemLoad.
func (s *Performance) GetMemLoad() float32 {
	return s.MemLoad
}

// GetOpenConnections returns the value of OpenConnections.
func (s *Performance) GetOpenConnections() int32 {
	return s.OpenConnections
}

// SetCpuLoad sets the value of CpuLoad.
func (s *Performance) SetCpuLoad(val float32) {
	s.CpuLoad = val
}

// SetRamLoad sets the value of RamLoad.
func (s *Performance) SetRamLoad(val float32) {
	s.RamLoad = val
}

// SetMemLoad sets the value of MemLoad.
func (s *Performance) SetMemLoad(val float32) {
	s.MemLoad = val
}

// SetOpenConnections sets the value of OpenConnections.
func (s *Performance) SetOpenConnections(val int32) {
	s.OpenConnections = val
}

// Status of the service.
// Ref: #/ServiceStatus
type ServiceStatus string

const (
	ServiceStatusUnknown ServiceStatus = "unknown"
	ServiceStatusStopped ServiceStatus = "stopped"
	ServiceStatusRunning ServiceStatus = "running"
)

// AllValues returns all ServiceStatus values.
func (ServiceStatus) AllValues() []ServiceStatus {
	return []ServiceStatus{
		ServiceStatusUnknown,
		ServiceStatusStopped,
		ServiceStatusRunning,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ServiceStatus) MarshalText() ([]byte, error) {
	switch s {
	case ServiceStatusUnknown:
		return []byte(s), nil
	case ServiceStatusStopped:
		return []byte(s), nil
	case ServiceStatusRunning:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ServiceStatus) UnmarshalText(data []byte) error {
	switch ServiceStatus(data) {
	case ServiceStatusUnknown:
		*s = ServiceStatusUnknown
		return nil
	case ServiceStatusStopped:
		*s = ServiceStatusStopped
		return nil
	case ServiceStatusRunning:
		*s = ServiceStatusRunning
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/StartRequest
type StartRequest struct {
	Users []User `json:"users"`
}

// GetUsers returns the value of Users.
func (s *StartRequest) GetUsers() []User {
	return s.Users
}

// SetUsers sets the value of Users.
func (s *StartRequest) SetUsers(val []User) {
	s.Users = val
}

// Ref: #/StartResponse
type StartResponse struct {
	ClientConfigTemplate ClientConfigTemplate `json:"clientConfigTemplate"`
	Version              string               `json:"version"`
}

// GetClientConfigTemplate returns the value of ClientConfigTemplate.
func (s *StartResponse) GetClientConfigTemplate() ClientConfigTemplate {
	return s.ClientConfigTemplate
}

// GetVersion returns the value of Version.
func (s *StartResponse) GetVersion() string {
	return s.Version
}

// SetClientConfigTemplate sets the value of ClientConfigTemplate.
func (s *StartResponse) SetClientConfigTemplate(val ClientConfigTemplate) {
	s.ClientConfigTemplate = val
}

// SetVersion sets the value of Version.
func (s *StartResponse) SetVersion(val string) {
	s.Version = val
}

// Ref: #/StatsResponse
type StatsResponse struct {
	Users       []UserStat  `json:"users"`
	Performance Performance `json:"performance"`
}

// GetUsers returns the value of Users.
func (s *StatsResponse) GetUsers() []UserStat {
	return s.Users
}

// GetPerformance returns the value of Performance.
func (s *StatsResponse) GetPerformance() Performance {
	return s.Performance
}

// SetUsers sets the value of Users.
func (s *StatsResponse) SetUsers(val []UserStat) {
	s.Users = val
}

// SetPerformance sets the value of Performance.
func (s *StatsResponse) SetPerformance(val Performance) {
	s.Performance = val
}

// Ref: #/StatusResponse
type StatusResponse struct {
	ServiceStatus ServiceStatus `json:"serviceStatus"`
}

// GetServiceStatus returns the value of ServiceStatus.
func (s *StatusResponse) GetServiceStatus() ServiceStatus {
	return s.ServiceStatus
}

// SetServiceStatus sets the value of ServiceStatus.
func (s *StatusResponse) SetServiceStatus(val ServiceStatus) {
	s.ServiceStatus = val
}

// StopOK is response for Stop operation.
type StopOK struct{}

// Ref: #/User
type User struct {
	ID        UserID `json:"ID"`
	Name      string `json:"name"`
	VlessUUID string `json:"vlessUUID"`
}

// GetID returns the value of ID.
func (s *User) GetID() UserID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetVlessUUID returns the value of VlessUUID.
func (s *User) GetVlessUUID() string {
	return s.VlessUUID
}

// SetID sets the value of ID.
func (s *User) SetID(val UserID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetVlessUUID sets the value of VlessUUID.
func (s *User) SetVlessUUID(val string) {
	s.VlessUUID = val
}

type UserID int

// User data usage statistics.
// Ref: #/UserStat
type UserStat struct {
	ID       UserID `json:"ID"`
	Uplink   int64  `json:"Uplink"`
	Downlink int64  `json:"Downlink"`
}

// GetID returns the value of ID.
func (s *UserStat) GetID() UserID {
	return s.ID
}

// GetUplink returns the value of Uplink.
func (s *UserStat) GetUplink() int64 {
	return s.Uplink
}

// GetDownlink returns the value of Downlink.
func (s *UserStat) GetDownlink() int64 {
	return s.Downlink
}

// SetID sets the value of ID.
func (s *UserStat) SetID(val UserID) {
	s.ID = val
}

// SetUplink sets the value of Uplink.
func (s *UserStat) SetUplink(val int64) {
	s.Uplink = val
}

// SetDownlink sets the value of Downlink.
func (s *UserStat) SetDownlink(val int64) {
	s.Downlink = val
}
