// Code generated by ogen, DO NOT EDIT.

package ogenclient

// OperationName is the ogen operation name
type OperationName = string

const (
	EditUsersOperation OperationName = "EditUsers"
	GetStatsOperation  OperationName = "GetStats"
	GetStatusOperation OperationName = "GetStatus"
	StartOperation     OperationName = "Start"
	StopOperation      OperationName = "Stop"
)
