services:
  xray-nodeman:
    image: ghcr.io/xray-addons/xray-nodeman:VERSION_PLACEHOLDER
    container_name: xray-nodeman
    restart: unless-stopped
    ports:
      - "8080:80"
      - "9090:9090"
    environment:
      XRAY_NODEMAN_ENDPOINT: "0.0.0.0:80"
      XRAY_NODEMAN_METRICS_ENDPOINT: "0.0.0.0:9090"
      XRAY_NODEMAN_DB: ${XRAY_NODEMAN_DB:?Set XRAY_NODEMAN_DB in .env file}
      XRAY_NODEMAN_JWT: ${XRAY_NODEMAN_JWT:?Set XRAY_NODEMAN_JWT in .env file}
      XRAY_NODEMAN_ADM_PASS: ${XRAY_NODEMAN_ADM_PASS:?Set XRAY_NODEMAN_ADM_PASS in .env file}
