// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	gen "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
)

func ConvertClientCfg(source gen.ClientCfg) models.ClientConfig {
	var modelsClientCfg models.ClientConfig
	modelsClientCfg.Template = source.Template
	modelsClientCfg.UserNameField = source.UserNameField
	modelsClientCfg.VlessUUIDField = source.VlessUUIDField
	return modelsClientCfg
}
func ConvertUsers(source []models.UserProfile) []gen.User {
	var apiUserList []gen.User
	if source != nil {
		apiUserList = make([]gen.User, len(source))
		for i := 0; i < len(source); i++ {
			apiUserList[i] = modelsUserProfileToApiUser(source[i])
		}
	}
	return apiUserList
}
func ConvertUsersUpdate(source models.NodeUsersUpdate) gen.EditUsersRequest {
	var apiEditUsersRequest gen.EditUsersRequest
	apiEditUsersRequest.Add = ConvertUsers(source.Add)
	apiEditUsersRequest.Remove = ConvertUsers(source.Remove)
	return apiEditUsersRequest
}
func modelsUserProfileToApiUser(source models.UserProfile) gen.User {
	var apiUser gen.User
	apiUser.Name = source.Name
	apiUser.VlessUUID = source.VlessUUID
	return apiUser
}
