// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	gen "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	jx "github.com/go-faster/jx"
)

func ConvertClientConfig(source gen.ClientConfigTemplate) models.ClientConfigTemplate {
	var modelsClientConfigTemplate models.ClientConfigTemplate
	if source.Template != nil {
		modelsClientConfigTemplate.Template = make([]jx.Raw, len(source.Template))
		for i := 0; i < len(source.Template); i++ {
			modelsClientConfigTemplate.Template[i] = apiClientConfigTemplateItemToJxRaw(source.Template[i])
		}
	}
	modelsClientConfigTemplate.VlessEmailField = source.VlessEmailField
	modelsClientConfigTemplate.VlessUUIDField = source.VlessUUIDField
	return modelsClientConfigTemplate
}
func ConvertUsers(source []models.UserProfile) []gen.User {
	var apiUserList []gen.User
	if source != nil {
		apiUserList = make([]gen.User, len(source))
		for i := 0; i < len(source); i++ {
			apiUserList[i] = modelsUserProfileToApiUser(source[i])
		}
	}
	return apiUserList
}
func ConvertUsersUpdate(source models.NodeUsersUpdate) gen.EditUsersRequest {
	var apiEditUsersRequest gen.EditUsersRequest
	apiEditUsersRequest.Add = ConvertUsers(source.Add)
	apiEditUsersRequest.Remove = ConvertUsers(source.Remove)
	return apiEditUsersRequest
}
func apiClientConfigTemplateItemToJxRaw(source gen.ClientConfigTemplateItem) jx.Raw {
	var jxRaw jx.Raw
	if source != nil {
		jxRaw = make(jx.Raw, len(source))
		for i := 0; i < len(source); i++ {
			jxRaw[i] = source[i]
		}
	}
	return jxRaw
}
func modelsUserProfileToApiUser(source models.UserProfile) gen.User {
	var apiUser gen.User
	apiUser.ID = gen.UserID(source.ID)
	apiUser.Name = source.Name
	apiUser.VlessUUID = source.VlessUUID
	return apiUser
}
