openapi: 3.0.3
info:
  title: Node Management API
  version: 1.0.0

paths:
  /nodes/new:
    post:
      summary: Create a new node
      operationId: NewNode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewNodeRequest'
      responses:
        '200':
          description: Created node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewNodeResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nodes/start:
    post:
      summary: Start a node
      operationId: StartNode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartNodeRequest'
      responses:
        '200':
          description: Start result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartNodeResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nodes/stop:
    post:
      summary: Stop a node
      operationId: StopNode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StopNodeRequest'
      responses:
        '200':
          description: Stop result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopNodeResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /nodes:
    get:
      summary: List all nodes
      operationId: ListNodes
      parameters: []
      responses:
        '200':
          description: List of nodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNodeResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/new:
    post:
      summary: Create a new user
      operationId: NewUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '200':
          description: Created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUserResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/enable:
    post:
      summary: Enable a user on all nodes
      operationId: EnableUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnableUserRequest'
      responses:
        '200':
          description: User enabled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnableUserResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/disable:
    post:
      summary: Disable a user from all nodes
      operationId: DisableUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisableUserRequest'
      responses:
        '200':
          description: User disabled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisableUserResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      summary: List all users
      operationId: ListUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsersResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sub/{ID}-{Name}:
    get:
      summary: Get subscription by user
      operationId: GetUserSub
      parameters:
        - name: ID
          in: path
          required: true
          description: User ID
          schema:
            $ref: '#/components/schemas/UserID'
        - name: Name
          in: path
          required: true
          description: User name
          schema:
            type: string
      responses:
        '200':
          description: List of subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserSubResponse'
        'default':
          description: General Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    NodeID:
      type: integer

    NodeStatus:
      type: string
      enum: [unknown, stopped, running]

    ClientConfig:
      type: object
      properties:
        Template:
          type: string
        UserNameField:
          type: string
        VlessUUIDField:
          type: string
      required:
        - Template
        - UserNameField
        - VlessUUIDField

    NodeConnectionInfo:
      type: object
      properties:
        Endpoint:
          type: string
        AccessKey:
          type: string
      required:
        - Endpoint
        - AccessKey

    NodeConfig:
      type: object
      properties:
        ClientConfig:
          $ref: '#/components/schemas/ClientConfig'
        ConnectionInfo:
          $ref: '#/components/schemas/NodeConnectionInfo'
      required:
        - ClientConfig
        - ConnectionInfo

    Node:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/NodeID'
        Config:
          $ref: '#/components/schemas/NodeConfig'
        CurrentStatus:
          $ref: '#/components/schemas/NodeStatus'
        TargetStatus:
          $ref: '#/components/schemas/NodeStatus'
      required:
        - ID
        - Config
        - CurrentStatus
        - TargetStatus

    NewNodeRequest:
      type: object
      properties:
        Endpoint:
          type: string
        AccessKey:
          type: string
          minLength: 88
          maxLength: 88
          description: Base64-encoded 32-byte access secret + 32-byte cert hash
      required:
        - Endpoint
        - AccessKey

    NewNodeResponse:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/NodeID'
        Endpoint:
          type: string
      required:
        - ID
        - Endpoint

    StartNodeRequest:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/NodeID'
      required:
        - ID

    StartNodeResponse:
      type: object
      properties: {}

    StopNodeRequest:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/NodeID'
      required:
        - ID

    StopNodeResponse:
      type: object
      properties: {}

    ListNodeRequest:
      type: object
      properties: {}

    ListNodeResponse:
      type: object
      properties:
        Nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
      required:
        - Nodes

    UserID:
      type: integer

    UserStatus:
      type: string
      enum: [unknown, enabled, disabled]

    UserProfile:
      type: object
      properties:
        Name:
          type: string
        VisibleName:
          type: string
        VlessUUID:
          type: string
      required:
        - Name
        - VisibleName
        - VlessUUID

    User:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/UserID'
        Profile:
          $ref: '#/components/schemas/UserProfile'
        TargetStatus:
          $ref: '#/components/schemas/UserStatus'
      required:
        - ID
        - Profile
        - TargetStatus

    NewUserRequest:
      type: object
      properties:
        VisibleName:
          type: string
      required:
        - VisibleName

    NewUserResponse:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/UserID'
        VisibleName:
          type: string
        UserPageURL:
          type: string
      required:
        - ID
        - VisibleName
        - UserPageURL

    EnableUserRequest:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/UserID'
      required:
        - ID

    EnableUserResponse:
      type: object
      properties: {}

    DisableUserRequest:
      type: object
      properties:
        ID:
          $ref: '#/components/schemas/UserID'
      required:
        - ID

    DisableUserResponse:
      type: object
      properties: {}

    ListUsersResponse:
      type: object
      properties:
        Users:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - Users

    Subscription:
      type: object
      description: "subscription json object"
      additionalProperties: true

    GetUserSubResponse:
      type: array
      items:
        $ref: '#/components/schemas/Subscription'

    Error:
      type: object
      properties:
        Message:
          type: string
        Details:
          type: string
          nullable: true
      required:
        - Message
