// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	pagecfg "github.com/XRay-Addons/xrayman/nodeman/internal/pages/pagecfg"
	schemas "github.com/XRay-Addons/xrayman/nodeman/internal/pages/schemas"
)

func ConvertAdminPageCfg(source pagecfg.AdminPageCfg) schemas.AdminpagecfgJson {
	var schemasAdminpagecfgJson schemas.AdminpagecfgJson
	schemasAdminpagecfgJson.AdminPrefix = source.AdminPrefix
	schemasAdminpagecfgJson.ApiPrefix = source.ApiPrefix
	if source.SettingsTags != nil {
		schemasAdminpagecfgJson.SettingsTags = make([]string, len(source.SettingsTags))
		for i := 0; i < len(source.SettingsTags); i++ {
			schemasAdminpagecfgJson.SettingsTags[i] = source.SettingsTags[i]
		}
	}
	schemasAdminpagecfgJson.UserPrefix = source.UserPrefix
	return schemasAdminpagecfgJson
}
func ConvertUserPageCfg(source pagecfg.UserPageCfg) schemas.UserpagecfgJson {
	var schemasUserpagecfgJson schemas.UserpagecfgJson
	schemasUserpagecfgJson.ApiPrefix = source.ApiPrefix
	if source.AppLinks != nil {
		schemasUserpagecfgJson.AppLinks = make([]schemas.UserpagecfgJsonAppLinksElem, len(source.AppLinks))
		for i := 0; i < len(source.AppLinks); i++ {
			schemasUserpagecfgJson.AppLinks[i] = modelsAppLinkToSchemasUserpagecfgJsonAppLinksElem(source.AppLinks[i])
		}
	}
	schemasUserpagecfgJson.SupportLink = source.SupportLink
	schemasUserpagecfgJson.UserPrefix = source.UserPrefix
	return schemasUserpagecfgJson
}
func modelsAppLinkToSchemasUserpagecfgJsonAppLinksElem(source models.AppLink) schemas.UserpagecfgJsonAppLinksElem {
	var schemasUserpagecfgJsonAppLinksElem schemas.UserpagecfgJsonAppLinksElem
	schemasUserpagecfgJsonAppLinksElem.Name = source.Name
	schemasUserpagecfgJsonAppLinksElem.Platforms = source.Platforms
	schemasUserpagecfgJsonAppLinksElem.URL = source.URL
	return schemasUserpagecfgJsonAppLinksElem
}
