openapi: 3.0.3
info:
  title: Node Management API
  version: 1.0.0

paths:
  /auth:
    $ref: "./paths/auth.yaml#/Auth"

  /nodes/new:
    $ref: "./paths/nodes.yaml#/NewNode"

  /nodes/start:
    $ref: "./paths/nodes.yaml#/StartNode"

  /nodes/stop:
    $ref: "./paths/nodes.yaml#/StopNode"

  /nodes/delete:
    $ref: "./paths/nodes.yaml#/DeleteNode"

  /nodes:
    $ref: "./paths/nodes.yaml#/ListNodes"

  /user/new:
    $ref: "./paths/users.yaml#/NewUser"

  /user/enable:
    $ref: "./paths/users.yaml#/EnableUser"

  /user/disable:
    $ref: "./paths/users.yaml#/DisableUser"

  /user/delete:
    $ref: "./paths/users.yaml#/DeleteUser"

  /user/{ID}-{Name}:
    $ref: "./paths/users.yaml#/GetUser"

  /users:
    $ref: "./paths/users.yaml#/ListUsers"

  /sub/{ID}-{Name}:
    $ref: "./paths/subscriptions.yaml#/GetSubscription"

  /settings/get:
    $ref: "./paths/settings.yaml#/GetSettings"

  /settings/set:
    $ref: "./paths/settings.yaml#/SetSettings"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
