// Code generated by MockGen. DO NOT EDIT.
// Source: pool_syncer.go
//
// Generated by this command:
//
//	mockgen -source=pool_syncer.go -destination=./mocks/mock_pool_syncer.go -package=mocks PoolSyncer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPoolSyncer is a mock of PoolSyncer interface.
type MockPoolSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockPoolSyncerMockRecorder
	isgomock struct{}
}

// MockPoolSyncerMockRecorder is the mock recorder for MockPoolSyncer.
type MockPoolSyncerMockRecorder struct {
	mock *MockPoolSyncer
}

// NewMockPoolSyncer creates a new mock instance.
func NewMockPoolSyncer(ctrl *gomock.Controller) *MockPoolSyncer {
	mock := &MockPoolSyncer{ctrl: ctrl}
	mock.recorder = &MockPoolSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoolSyncer) EXPECT() *MockPoolSyncerMockRecorder {
	return m.recorder
}

// SyncPoolState mocks base method.
func (m *MockPoolSyncer) SyncPoolState(ctx context.Context) (*models.PoolSyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPoolState", ctx)
	ret0, _ := ret[0].(*models.PoolSyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncPoolState indicates an expected call of SyncPoolState.
func (mr *MockPoolSyncerMockRecorder) SyncPoolState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPoolState", reflect.TypeOf((*MockPoolSyncer)(nil).SyncPoolState), ctx)
}
