/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdminPageConfig {
  /**
   * prefix for api requests
   */
  ApiPrefix: string;
  /**
   * prefix for admin page spa
   */
  AdminPrefix: string;
  /**
   * prefix for user page spa
   */
  UserPrefix: string;
  /**
   * List of allowed settings placeholders
   */
  SettingsTags: string[];
}
