/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AdminPageConfig {
  routes: {
    /**
     * prefix for api requests
     */
    api_prefix: string;
    /**
     * prefix for admin page spa
     */
    admin_prefix: string;
    /**
     * prefix for user page spa
     */
    user_prefix: string;
  };
  /**
   * List of allowed subscription header placeholders
   */
  sub_headers_placeholders: string[];
}
