// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gen "github.com/XRay-Addons/xrayman/nodeman/pkg/api/http/gen"
	jx "github.com/go-faster/jx"
)

func ConvertAuthRequest(source *gen.AuthRequest) (*models.AuthParams, error) {
	var pModelsAuthParams *models.AuthParams
	if source != nil {
		var modelsAuthParams models.AuthParams
		modelsAuthParams.Password = (*source).Password
		pModelsAuthParams = &modelsAuthParams
	}
	return pModelsAuthParams, nil
}
func ConvertAuthResult(source *models.AuthResult) *gen.AuthResponse {
	var pApiAuthResponse *gen.AuthResponse
	if source != nil {
		var apiAuthResponse gen.AuthResponse
		apiAuthResponse.AccessToken = (*source).AccessToken
		apiAuthResponse.TokenType = (*source).TokenType
		apiAuthResponse.ExpiresIn = ConvertExpireTime((*source).ExpiresIn)
		pApiAuthResponse = &apiAuthResponse
	}
	return pApiAuthResponse
}
func ConvertDeleteNodeRequest(source *gen.DeleteNodeRequest) (*models.DeleteNodeParams, error) {
	var pModelsDeleteNodeParams *models.DeleteNodeParams
	if source != nil {
		var modelsDeleteNodeParams models.DeleteNodeParams
		modelsDeleteNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsDeleteNodeParams = &modelsDeleteNodeParams
	}
	return pModelsDeleteNodeParams, nil
}
func ConvertDeleteUserRequest(source *gen.DeleteUserRequest) (*models.DeleteUserParams, error) {
	var pModelsDeleteUserParams *models.DeleteUserParams
	if source != nil {
		var modelsDeleteUserParams models.DeleteUserParams
		modelsDeleteUserParams.ID = RConvertUserID((*source).ID)
		pModelsDeleteUserParams = &modelsDeleteUserParams
	}
	return pModelsDeleteUserParams, nil
}
func ConvertDisableUserRequest(source *gen.DisableUserRequest) (*models.DisableUserParams, error) {
	var pModelsDisableUserParams *models.DisableUserParams
	if source != nil {
		var modelsDisableUserParams models.DisableUserParams
		modelsDisableUserParams.ID = RConvertUserID((*source).ID)
		pModelsDisableUserParams = &modelsDisableUserParams
	}
	return pModelsDisableUserParams, nil
}
func ConvertEnableUserRequest(source *gen.EnableUserRequest) (*models.EnableUserParams, error) {
	var pModelsEnableUserParams *models.EnableUserParams
	if source != nil {
		var modelsEnableUserParams models.EnableUserParams
		modelsEnableUserParams.ID = RConvertUserID((*source).ID)
		pModelsEnableUserParams = &modelsEnableUserParams
	}
	return pModelsEnableUserParams, nil
}
func ConvertGetUserRequest(source *gen.GetUserParams) (*models.GetUserParams, error) {
	var pModelsGetUserParams *models.GetUserParams
	if source != nil {
		var modelsGetUserParams models.GetUserParams
		modelsGetUserParams.ID = RConvertUserID((*source).ID)
		modelsGetUserParams.Name = (*source).Name
		pModelsGetUserParams = &modelsGetUserParams
	}
	return pModelsGetUserParams, nil
}
func ConvertListNodesResult(source *models.ListNodeResult) *gen.ListNodeResponse {
	var pApiListNodeResponse *gen.ListNodeResponse
	if source != nil {
		var apiListNodeResponse gen.ListNodeResponse
		if (*source).Nodes != nil {
			apiListNodeResponse.Nodes = make([]gen.Node, len((*source).Nodes))
			for i := 0; i < len((*source).Nodes); i++ {
				apiListNodeResponse.Nodes[i] = modelsNodeToApiNode((*source).Nodes[i])
			}
		}
		pApiListNodeResponse = &apiListNodeResponse
	}
	return pApiListNodeResponse
}
func ConvertListUsersResult(source *models.ListUsersResult) *gen.ListUsersResponse {
	var pApiListUsersResponse *gen.ListUsersResponse
	if source != nil {
		var apiListUsersResponse gen.ListUsersResponse
		if (*source).Users != nil {
			apiListUsersResponse.Users = make([]gen.User, len((*source).Users))
			for i := 0; i < len((*source).Users); i++ {
				apiListUsersResponse.Users[i] = modelsUserToApiUser((*source).Users[i])
			}
		}
		pApiListUsersResponse = &apiListUsersResponse
	}
	return pApiListUsersResponse
}
func ConvertNewNodeRequest(source *gen.NewNodeRequest) (*models.NewNodeParams, error) {
	var pModelsNewNodeParams *models.NewNodeParams
	if source != nil {
		var modelsNewNodeParams models.NewNodeParams
		modelsNewNodeParams.Endpoint = (*source).Endpoint
		modelsAccessKey, err := ConvertAccessKey((*source).AccessKey)
		if err != nil {
			return nil, err
		}
		modelsNewNodeParams.AccessKey = modelsAccessKey
		pModelsNewNodeParams = &modelsNewNodeParams
	}
	return pModelsNewNodeParams, nil
}
func ConvertNewNodeResult(source *models.NewNodeResult) *gen.NewNodeResponse {
	var pApiNewNodeResponse *gen.NewNodeResponse
	if source != nil {
		var apiNewNodeResponse gen.NewNodeResponse
		apiNewNodeResponse.Node = modelsNodeToApiNode((*source).Node)
		pApiNewNodeResponse = &apiNewNodeResponse
	}
	return pApiNewNodeResponse
}
func ConvertNewUserRequest(source *gen.NewUserRequest) (*models.NewUserParams, error) {
	var pModelsNewUserParams *models.NewUserParams
	if source != nil {
		var modelsNewUserParams models.NewUserParams
		modelsNewUserParams.DisplayName = (*source).DisplayName
		pModelsNewUserParams = &modelsNewUserParams
	}
	return pModelsNewUserParams, nil
}
func ConvertProfile(source models.UserProfile) gen.UserProfile {
	var apiUserProfile gen.UserProfile
	apiUserProfile.ID = ConvertUserID(source.ID)
	apiUserProfile.Name = source.Name
	apiUserProfile.DisplayName = source.DisplayName
	apiUserProfile.VlessUUID = source.VlessUUID
	apiUserProfile.SubscriptionPath = GetUserSubscription(source)
	return apiUserProfile
}
func ConvertStartNodeRequest(source *gen.StartNodeRequest) (*models.StartNodeParams, error) {
	var pModelsStartNodeParams *models.StartNodeParams
	if source != nil {
		var modelsStartNodeParams models.StartNodeParams
		modelsStartNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStartNodeParams = &modelsStartNodeParams
	}
	return pModelsStartNodeParams, nil
}
func ConvertStopNodeRequest(source *gen.StopNodeRequest) (*models.StopNodeParams, error) {
	var pModelsStopNodeParams *models.StopNodeParams
	if source != nil {
		var modelsStopNodeParams models.StopNodeParams
		modelsStopNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStopNodeParams = &modelsStopNodeParams
	}
	return pModelsStopNodeParams, nil
}
func ConvertUser(source *models.User) *gen.User {
	var pApiUser *gen.User
	if source != nil {
		apiUser := modelsUserToApiUser((*source))
		pApiUser = &apiUser
	}
	return pApiUser
}
func ConvertUserSubRequest(source *gen.UserSubParams) (*models.UserSubParams, error) {
	var pModelsUserSubParams *models.UserSubParams
	if source != nil {
		var modelsUserSubParams models.UserSubParams
		modelsUserSubParams.ID = RConvertUserID((*source).ID)
		modelsUserSubParams.Name = (*source).Name
		pModelsUserSubParams = &modelsUserSubParams
	}
	return pModelsUserSubParams, nil
}
func ConvertUserSubResult(source *models.UserSubResult) (*gen.UserSubResponseHeaders, error) {
	var pApiUserSubResponseHeaders *gen.UserSubResponseHeaders
	if source != nil {
		var apiUserSubResponseHeaders gen.UserSubResponseHeaders
		apiUserSubResponseHeaders.Expiration = (*source).Expiration
		apiUserSubResponseHeaders.Response = jxRawListToApiUserSubResponse((*source).ClientConfigs)
		pApiUserSubResponseHeaders = &apiUserSubResponseHeaders
	}
	return pApiUserSubResponseHeaders, nil
}
func jxRawListToApiUserSubResponse(source []jx.Raw) gen.UserSubResponse {
	var apiUserSubResponse gen.UserSubResponse
	if source != nil {
		apiUserSubResponse = make(gen.UserSubResponse, len(source))
		for i := 0; i < len(source); i++ {
			apiUserSubResponse[i] = jxRawToApiClientConfigItem(source[i])
		}
	}
	return apiUserSubResponse
}
func jxRawToApiClientConfigItem(source jx.Raw) gen.ClientConfigItem {
	var apiClientConfigItem gen.ClientConfigItem
	if source != nil {
		apiClientConfigItem = make(gen.ClientConfigItem, len(source))
		for i := 0; i < len(source); i++ {
			apiClientConfigItem[i] = source[i]
		}
	}
	return apiClientConfigItem
}
func jxRawToApiClientConfigTemplateItem(source jx.Raw) gen.ClientConfigTemplateItem {
	var apiClientConfigTemplateItem gen.ClientConfigTemplateItem
	if source != nil {
		apiClientConfigTemplateItem = make(gen.ClientConfigTemplateItem, len(source))
		for i := 0; i < len(source); i++ {
			apiClientConfigTemplateItem[i] = source[i]
		}
	}
	return apiClientConfigTemplateItem
}
func modelsClientConfigTemplateToApiClientConfigTemplate(source models.ClientConfigTemplate) gen.ClientConfigTemplate {
	var apiClientConfigTemplate gen.ClientConfigTemplate
	if source.Template != nil {
		apiClientConfigTemplate.Template = make([]gen.ClientConfigTemplateItem, len(source.Template))
		for i := 0; i < len(source.Template); i++ {
			apiClientConfigTemplate.Template[i] = jxRawToApiClientConfigTemplateItem(source.Template[i])
		}
	}
	apiClientConfigTemplate.VlessEmailField = source.VlessEmailField
	apiClientConfigTemplate.VlessUUIDField = source.VlessUUIDField
	return apiClientConfigTemplate
}
func modelsNodeConfigToApiNodeConfig(source models.NodeConfig) gen.NodeConfig {
	var apiNodeConfig gen.NodeConfig
	apiNodeConfig.ClientConfigTemplate = modelsClientConfigTemplateToApiClientConfigTemplate(source.ClientConfigTemplate)
	apiNodeConfig.ConnectionInfo = modelsNodeConnectionInfoToApiNodeConnectionInfo(source.ConnectionInfo)
	return apiNodeConfig
}
func modelsNodeConnectionInfoToApiNodeConnectionInfo(source models.NodeConnectionInfo) gen.NodeConnectionInfo {
	var apiNodeConnectionInfo gen.NodeConnectionInfo
	apiNodeConnectionInfo.Endpoint = source.Endpoint
	apiNodeConnectionInfo.AccessKey = RConvertAccessKey(source.AccessKey)
	return apiNodeConnectionInfo
}
func modelsNodeToApiNode(source models.Node) gen.Node {
	var apiNode gen.Node
	apiNode.ID = ConvertNodeID(source.ID)
	apiNode.Config = modelsNodeConfigToApiNodeConfig(source.Config)
	apiNode.CurrentStatus = ConvertNodeStatusResult(source.CurrentStatus)
	apiNode.TargetStatus = ConvertNodeStatusResult(source.TargetStatus)
	return apiNode
}
func modelsUserToApiUser(source models.User) gen.User {
	var apiUser gen.User
	apiUser.Profile = ConvertProfile(source.Profile)
	apiUser.TargetStatus = ConvertUserStatusResult(source.TargetStatus)
	return apiUser
}
