// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gen "github.com/XRay-Addons/xrayman/nodeman/pkg/api/http/gen"
)

func ConvertListNodesResult(source *models.ListNodeResult) *gen.ListNodeResponse {
	var pApiListNodeResponse *gen.ListNodeResponse
	if source != nil {
		var apiListNodeResponse gen.ListNodeResponse
		if (*source).Nodes != nil {
			apiListNodeResponse.Nodes = make([]gen.Node, len((*source).Nodes))
			for i := 0; i < len((*source).Nodes); i++ {
				apiListNodeResponse.Nodes[i] = modelsNodeToApiNode((*source).Nodes[i])
			}
		}
		pApiListNodeResponse = &apiListNodeResponse
	}
	return pApiListNodeResponse
}
func ConvertNewNodeRequest(source *gen.NewNodeRequest) (*models.NewNodeParams, error) {
	var pModelsNewNodeParams *models.NewNodeParams
	if source != nil {
		var modelsNewNodeParams models.NewNodeParams
		modelsNewNodeParams.Endpoint = (*source).Endpoint
		byteList, err := ConvertCertHash((*source).CertHash)
		if err != nil {
			return nil, err
		}
		modelsNewNodeParams.CertHash = byteList
		byteList2, err := ConvertCertHash((*source).AccessSecret)
		if err != nil {
			return nil, err
		}
		modelsNewNodeParams.AccessSecret = byteList2
		pModelsNewNodeParams = &modelsNewNodeParams
	}
	return pModelsNewNodeParams, nil
}
func ConvertNewNodeResult(source *models.NewNodeResult) *gen.NewNodeResponse {
	var pApiNewNodeResponse *gen.NewNodeResponse
	if source != nil {
		var apiNewNodeResponse gen.NewNodeResponse
		apiNewNodeResponse.ID = ConvertNodeID((*source).ID)
		apiNewNodeResponse.Endpoint = (*source).Endpoint
		pApiNewNodeResponse = &apiNewNodeResponse
	}
	return pApiNewNodeResponse
}
func ConvertStartNodeRequest(source *gen.StartNodeRequest) (*models.StartNodeParams, error) {
	var pModelsStartNodeParams *models.StartNodeParams
	if source != nil {
		var modelsStartNodeParams models.StartNodeParams
		modelsStartNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStartNodeParams = &modelsStartNodeParams
	}
	return pModelsStartNodeParams, nil
}
func ConvertStopNodeRequest(source *gen.StopNodeRequest) (*models.StopNodeParams, error) {
	var pModelsStopNodeParams *models.StopNodeParams
	if source != nil {
		var modelsStopNodeParams models.StopNodeParams
		modelsStopNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStopNodeParams = &modelsStopNodeParams
	}
	return pModelsStopNodeParams, nil
}
func modelsClientConfigToApiClientConfig(source models.ClientConfig) gen.ClientConfig {
	var apiClientConfig gen.ClientConfig
	apiClientConfig.Template = source.Template
	apiClientConfig.UserNameField = source.UserNameField
	apiClientConfig.VlessUUIDField = source.VlessUUIDField
	return apiClientConfig
}
func modelsNodeConfigToApiNodeConfig(source models.NodeConfig) gen.NodeConfig {
	var apiNodeConfig gen.NodeConfig
	apiNodeConfig.ClientConfig = modelsClientConfigToApiClientConfig(source.ClientConfig)
	apiNodeConfig.ConnectionInfo = modelsNodeConnectionInfoToApiNodeConnectionInfo(source.ConnectionInfo)
	return apiNodeConfig
}
func modelsNodeConnectionInfoToApiNodeConnectionInfo(source models.NodeConnectionInfo) gen.NodeConnectionInfo {
	var apiNodeConnectionInfo gen.NodeConnectionInfo
	apiNodeConnectionInfo.Endpoint = source.Endpoint
	apiNodeConnectionInfo.AccessSecret = make([]uint8, len(source.AccessSecret))
	for i := 0; i < len(source.AccessSecret); i++ {
		apiNodeConnectionInfo.AccessSecret[i] = source.AccessSecret[i]
	}
	return apiNodeConnectionInfo
}
func modelsNodeToApiNode(source models.Node) gen.Node {
	var apiNode gen.Node
	apiNode.ID = ConvertNodeID(source.ID)
	apiNode.Config = modelsNodeConfigToApiNodeConfig(source.Config)
	apiNode.CurrentStatus = ConvertNodeStatusResult(source.CurrentStatus)
	apiNode.TargetStatus = ConvertNodeStatusResult(source.TargetStatus)
	return apiNode
}
