// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	"encoding/json"
	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gen "github.com/XRay-Addons/xrayman/nodeman/pkg/api/http/gen"
)

func ConvertDisableUserRequest(source *gen.DisableUserRequest) (*models.DisableUserParams, error) {
	var pModelsDisableUserParams *models.DisableUserParams
	if source != nil {
		var modelsDisableUserParams models.DisableUserParams
		modelsDisableUserParams.ID = RConvertUserID((*source).ID)
		pModelsDisableUserParams = &modelsDisableUserParams
	}
	return pModelsDisableUserParams, nil
}
func ConvertEnableUserRequest(source *gen.EnableUserRequest) (*models.EnableUserParams, error) {
	var pModelsEnableUserParams *models.EnableUserParams
	if source != nil {
		var modelsEnableUserParams models.EnableUserParams
		modelsEnableUserParams.ID = RConvertUserID((*source).ID)
		pModelsEnableUserParams = &modelsEnableUserParams
	}
	return pModelsEnableUserParams, nil
}
func ConvertListNodesResult(source *models.ListNodeResult) *gen.ListNodeResponse {
	var pApiListNodeResponse *gen.ListNodeResponse
	if source != nil {
		var apiListNodeResponse gen.ListNodeResponse
		if (*source).Nodes != nil {
			apiListNodeResponse.Nodes = make([]gen.Node, len((*source).Nodes))
			for i := 0; i < len((*source).Nodes); i++ {
				apiListNodeResponse.Nodes[i] = modelsNodeToApiNode((*source).Nodes[i])
			}
		}
		pApiListNodeResponse = &apiListNodeResponse
	}
	return pApiListNodeResponse
}
func ConvertListUsersResult(source *models.ListUsersResult) *gen.ListUsersResponse {
	var pApiListUsersResponse *gen.ListUsersResponse
	if source != nil {
		var apiListUsersResponse gen.ListUsersResponse
		if (*source).Users != nil {
			apiListUsersResponse.Users = make([]gen.User, len((*source).Users))
			for i := 0; i < len((*source).Users); i++ {
				apiListUsersResponse.Users[i] = modelsUserToApiUser((*source).Users[i])
			}
		}
		pApiListUsersResponse = &apiListUsersResponse
	}
	return pApiListUsersResponse
}
func ConvertNewNodeRequest(source *gen.NewNodeRequest) (*models.NewNodeParams, error) {
	var pModelsNewNodeParams *models.NewNodeParams
	if source != nil {
		var modelsNewNodeParams models.NewNodeParams
		modelsNewNodeParams.Endpoint = (*source).Endpoint
		modelsAccessKey, err := ConvertAccessKey((*source).AccessKey)
		if err != nil {
			return nil, err
		}
		modelsNewNodeParams.AccessKey = modelsAccessKey
		pModelsNewNodeParams = &modelsNewNodeParams
	}
	return pModelsNewNodeParams, nil
}
func ConvertNewNodeResult(source *models.NewNodeResult) *gen.NewNodeResponse {
	var pApiNewNodeResponse *gen.NewNodeResponse
	if source != nil {
		var apiNewNodeResponse gen.NewNodeResponse
		apiNewNodeResponse.ID = ConvertNodeID((*source).ID)
		apiNewNodeResponse.Endpoint = (*source).Endpoint
		pApiNewNodeResponse = &apiNewNodeResponse
	}
	return pApiNewNodeResponse
}
func ConvertNewUserRequest(source *gen.NewUserRequest) (*models.NewUserParams, error) {
	var pModelsNewUserParams *models.NewUserParams
	if source != nil {
		var modelsNewUserParams models.NewUserParams
		modelsNewUserParams.VisibleName = (*source).VisibleName
		pModelsNewUserParams = &modelsNewUserParams
	}
	return pModelsNewUserParams, nil
}
func ConvertNewUserResult(source *models.NewUserResult) *gen.NewUserResponse {
	var pApiNewUserResponse *gen.NewUserResponse
	if source != nil {
		var apiNewUserResponse gen.NewUserResponse
		apiNewUserResponse.ID = ConvertUserID((*source).ID)
		apiNewUserResponse.VisibleName = (*source).VisibleName
		apiNewUserResponse.UserPageURL = (*source).UserPageURL
		pApiNewUserResponse = &apiNewUserResponse
	}
	return pApiNewUserResponse
}
func ConvertStartNodeRequest(source *gen.StartNodeRequest) (*models.StartNodeParams, error) {
	var pModelsStartNodeParams *models.StartNodeParams
	if source != nil {
		var modelsStartNodeParams models.StartNodeParams
		modelsStartNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStartNodeParams = &modelsStartNodeParams
	}
	return pModelsStartNodeParams, nil
}
func ConvertStopNodeRequest(source *gen.StopNodeRequest) (*models.StopNodeParams, error) {
	var pModelsStopNodeParams *models.StopNodeParams
	if source != nil {
		var modelsStopNodeParams models.StopNodeParams
		modelsStopNodeParams.ID = RConvertNodeID((*source).ID)
		pModelsStopNodeParams = &modelsStopNodeParams
	}
	return pModelsStopNodeParams, nil
}
func ConvertUserSubRequest(source *gen.GetUserSubParams) (*models.GetUserSubParams, error) {
	var pModelsGetUserSubParams *models.GetUserSubParams
	if source != nil {
		var modelsGetUserSubParams models.GetUserSubParams
		modelsGetUserSubParams.ID = RConvertUserID((*source).ID)
		modelsGetUserSubParams.Name = (*source).Name
		pModelsGetUserSubParams = &modelsGetUserSubParams
	}
	return pModelsGetUserSubParams, nil
}
func ConvertUserSubResult(source *[]json.RawMessage) (*gen.GetUserSubResponse, error) {
	var pApiGetUserSubResponse *gen.GetUserSubResponse
	if source != nil {
		apiGetUserSubResponse, err := jsonRawMessageListToApiGetUserSubResponse((*source))
		if err != nil {
			return nil, err
		}
		pApiGetUserSubResponse = &apiGetUserSubResponse
	}
	return pApiGetUserSubResponse, nil
}
func jsonRawMessageListToApiGetUserSubResponse(source []json.RawMessage) (gen.GetUserSubResponse, error) {
	var apiGetUserSubResponse gen.GetUserSubResponse
	if source != nil {
		apiGetUserSubResponse = make(gen.GetUserSubResponse, len(source))
		for i := 0; i < len(source); i++ {
			apiSubscription, err := ConvertSubscription(source[i])
			if err != nil {
				return nil, err
			}
			apiGetUserSubResponse[i] = apiSubscription
		}
	}
	return apiGetUserSubResponse, nil
}
func modelsClientConfigToApiClientConfig(source models.ClientConfig) gen.ClientConfig {
	var apiClientConfig gen.ClientConfig
	apiClientConfig.Template = source.Template
	apiClientConfig.UserNameField = source.UserNameField
	apiClientConfig.VlessUUIDField = source.VlessUUIDField
	return apiClientConfig
}
func modelsNodeConfigToApiNodeConfig(source models.NodeConfig) gen.NodeConfig {
	var apiNodeConfig gen.NodeConfig
	apiNodeConfig.ClientConfig = modelsClientConfigToApiClientConfig(source.ClientConfig)
	apiNodeConfig.ConnectionInfo = modelsNodeConnectionInfoToApiNodeConnectionInfo(source.ConnectionInfo)
	return apiNodeConfig
}
func modelsNodeConnectionInfoToApiNodeConnectionInfo(source models.NodeConnectionInfo) gen.NodeConnectionInfo {
	var apiNodeConnectionInfo gen.NodeConnectionInfo
	apiNodeConnectionInfo.Endpoint = source.Endpoint
	apiNodeConnectionInfo.AccessKey = RConvertAccessKey(source.AccessKey)
	return apiNodeConnectionInfo
}
func modelsNodeToApiNode(source models.Node) gen.Node {
	var apiNode gen.Node
	apiNode.ID = ConvertNodeID(source.ID)
	apiNode.Config = modelsNodeConfigToApiNodeConfig(source.Config)
	apiNode.CurrentStatus = ConvertNodeStatusResult(source.CurrentStatus)
	apiNode.TargetStatus = ConvertNodeStatusResult(source.TargetStatus)
	return apiNode
}
func modelsUserProfileToApiUserProfile(source models.UserProfile) gen.UserProfile {
	var apiUserProfile gen.UserProfile
	apiUserProfile.Name = source.Name
	apiUserProfile.VisibleName = source.VisibleName
	apiUserProfile.VlessUUID = source.VlessUUID
	return apiUserProfile
}
func modelsUserToApiUser(source models.User) gen.User {
	var apiUser gen.User
	apiUser.ID = ConvertUserID(source.ID)
	apiUser.Profile = modelsUserProfileToApiUserProfile(source.Profile)
	apiUser.TargetStatus = ConvertUserStatusResult(source.TargetStatus)
	return apiUser
}
