/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Node Management API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type NodeID = number;

export type NodeStatus = typeof NodeStatus[keyof typeof NodeStatus];


export const NodeStatus = {
  unknown: 'unknown',
  stopped: 'stopped',
  running: 'running',
} as const;

/**
 * client config json template
 */
export interface ClientConfigTemplateItem {}

export interface ClientConfigTemplate {
  template: ClientConfigTemplateItem[];
  vlessEmailField: string;
  vlessUUIDField: string;
}

export interface NodeConnectionInfo {
  Endpoint: string;
  AccessKey: string;
}

export interface NodeConfig {
  ClientConfigTemplate: ClientConfigTemplate;
  ConnectionInfo: NodeConnectionInfo;
}

export interface Node {
  ID: NodeID;
  Config: NodeConfig;
  CurrentStatus: NodeStatus;
  TargetStatus: NodeStatus;
}

export interface NewNodeRequest {
  Endpoint: string;
  /**
   * Base64-encoded 32-byte access secret + 32-byte cert hash
   * @minLength 88
   * @maxLength 88
   */
  AccessKey: string;
}

export interface NewNodeResponse {
  ID: NodeID;
  Endpoint: string;
}

export interface StartNodeRequest {
  ID: NodeID;
}

export interface StartNodeResponse { [key: string]: unknown }

export interface StopNodeRequest {
  ID: NodeID;
}

export interface StopNodeResponse { [key: string]: unknown }

export interface ListNodeRequest { [key: string]: unknown }

export interface ListNodeResponse {
  Nodes: Node[];
}

export type UserID = number;

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


export const UserStatus = {
  unknown: 'unknown',
  enabled: 'enabled',
  disabled: 'disabled',
} as const;

export interface UserProfile {
  ID: UserID;
  Name: string;
  DisplayName: string;
  VlessUUID: string;
}

export interface User {
  Profile: UserProfile;
  TargetStatus: UserStatus;
}

export interface NewUserRequest {
  DisplayName: string;
}

export type NewUserResponse = User;

export interface GetUserRequest {
  ID: UserID;
  Name: string;
}

export type GetUserResponse = User;

export interface ListUsersResponse {
  Users: User[];
}

export interface EnableUserRequest {
  ID: UserID;
}

export interface EnableUserResponse { [key: string]: unknown }

export interface DisableUserRequest {
  ID: UserID;
}

export interface DisableUserResponse { [key: string]: unknown }

/**
 * subscription json object
 */
export interface ClientConfigItem {}

export type UserSubResponse = ClientConfigItem[];

export interface Error {
  Message: string;
  /** @nullable */
  Details?: string | null;
}

/**
 * List of subscription
 */
export type UserSubResponseResponse = UserSubResponse;

export const getNodeManagementAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Create a new node
 */
const newNode = (
    newNodeRequest: NewNodeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<NewNodeResponse>> => {
    return axiosInstance.post(
      `/nodes/new`,
      newNodeRequest,options
    );
  }

/**
 * @summary Start a node
 */
const startNode = (
    startNodeRequest: StartNodeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StartNodeResponse>> => {
    return axiosInstance.post(
      `/nodes/start`,
      startNodeRequest,options
    );
  }

/**
 * @summary Stop a node
 */
const stopNode = (
    stopNodeRequest: StopNodeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StopNodeResponse>> => {
    return axiosInstance.post(
      `/nodes/stop`,
      stopNodeRequest,options
    );
  }

/**
 * @summary List all nodes
 */
const listNodes = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListNodeResponse>> => {
    return axiosInstance.get(
      `/nodes`,options
    );
  }

/**
 * @summary Create a new user
 */
const newUser = (
    newUserRequest: NewUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axiosInstance.post(
      `/user/new`,
      newUserRequest,options
    );
  }

/**
 * @summary Enable a user on all nodes
 */
const enableUser = (
    enableUserRequest: EnableUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EnableUserResponse>> => {
    return axiosInstance.post(
      `/user/enable`,
      enableUserRequest,options
    );
  }

/**
 * @summary Disable a user from all nodes
 */
const disableUser = (
    disableUserRequest: DisableUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DisableUserResponse>> => {
    return axiosInstance.post(
      `/user/disable`,
      disableUserRequest,options
    );
  }

/**
 * @summary Get user properties
 */
const getUser = (
    id: UserID,
    name: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axiosInstance.get(
      `/user/${id}-${name}`,options
    );
  }

/**
 * @summary List all users
 */
const listUsers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListUsersResponse>> => {
    return axiosInstance.get(
      `/users`,options
    );
  }

/**
 * @summary Get subscription by user
 */
const userSub = (
    id: UserID,
    name: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserSubResponseResponse>> => {
    return axiosInstance.get(
      `/sub/${id}-${name}`,options
    );
  }

return {newNode,startNode,stopNode,listNodes,newUser,enableUser,disableUser,getUser,listUsers,userSub}};
export type NewNodeResult = AxiosResponse<NewNodeResponse>
export type StartNodeResult = AxiosResponse<StartNodeResponse>
export type StopNodeResult = AxiosResponse<StopNodeResponse>
export type ListNodesResult = AxiosResponse<ListNodeResponse>
export type NewUserResult = AxiosResponse<User>
export type EnableUserResult = AxiosResponse<EnableUserResponse>
export type DisableUserResult = AxiosResponse<DisableUserResponse>
export type GetUserResult = AxiosResponse<User>
export type ListUsersResult = AxiosResponse<ListUsersResponse>
export type UserSubResult = AxiosResponse<UserSubResponseResponse>
