// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	"fmt"
	models "github.com/XRay-Addons/xrayman/node/internal/models"
	gen "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
)

func ConvertEditUsersRequest(source *gen.EditUsersRequest) *models.EditUsersParams {
	var pModelsEditUsersParams *models.EditUsersParams
	if source != nil {
		var modelsEditUsersParams models.EditUsersParams
		if (*source).Add != nil {
			modelsEditUsersParams.Add = make([]models.User, len((*source).Add))
			for i := 0; i < len((*source).Add); i++ {
				modelsEditUsersParams.Add[i] = apiUserToModelsUser((*source).Add[i])
			}
		}
		if (*source).Remove != nil {
			modelsEditUsersParams.Remove = make([]models.User, len((*source).Remove))
			for j := 0; j < len((*source).Remove); j++ {
				modelsEditUsersParams.Remove[j] = apiUserToModelsUser((*source).Remove[j])
			}
		}
		pModelsEditUsersParams = &modelsEditUsersParams
	}
	return pModelsEditUsersParams
}
func ConvertStartRequest(source *gen.StartRequest) *models.StartParams {
	var pModelsStartParams *models.StartParams
	if source != nil {
		var modelsStartParams models.StartParams
		if (*source).Users != nil {
			modelsStartParams.Users = make([]models.User, len((*source).Users))
			for i := 0; i < len((*source).Users); i++ {
				modelsStartParams.Users[i] = apiUserToModelsUser((*source).Users[i])
			}
		}
		pModelsStartParams = &modelsStartParams
	}
	return pModelsStartParams
}
func ConvertStartResult(source *models.StartResult) *gen.StartResponse {
	var pApiStartResponse *gen.StartResponse
	if source != nil {
		var apiStartResponse gen.StartResponse
		apiStartResponse.ClientConfigTemplate = modelsClientConfigTemplateToApiClientConfigTemplate((*source).ClientConfigTemplate)
		pApiStartResponse = &apiStartResponse
	}
	return pApiStartResponse
}
func ConvertStatus(source models.ServiceStatus) gen.ServiceStatus {
	var apiServiceStatus gen.ServiceStatus
	switch source {
	case models.ServiceStatusRunning:
		apiServiceStatus = gen.ServiceStatusRunning
	case models.ServiceStatusStopped:
		apiServiceStatus = gen.ServiceStatusStopped
	case models.ServiceStatusUnknown:
		apiServiceStatus = gen.ServiceStatusUnknown
	default:
		panic(fmt.Sprintf("unexpected enum element: %v", source))
	}
	return apiServiceStatus
}
func ConvertStatusResult(source *models.StatusResult) *gen.StatusResponse {
	var pApiStatusResponse *gen.StatusResponse
	if source != nil {
		var apiStatusResponse gen.StatusResponse
		apiStatusResponse.ServiceStatus = ConvertStatus((*source).ServiceStatus)
		pApiStatusResponse = &apiStatusResponse
	}
	return pApiStatusResponse
}
func apiUserToModelsUser(source gen.User) models.User {
	var modelsUser models.User
	modelsUser.ID = models.UserID(source.ID)
	modelsUser.Name = source.Name
	modelsUser.VlessUUID = source.VlessUUID
	return modelsUser
}
func modelsClientConfigTemplateToApiClientConfigTemplate(source models.ClientConfigTemplate) gen.ClientConfigTemplate {
	var apiClientConfigTemplate gen.ClientConfigTemplate
	if source.Template != nil {
		apiClientConfigTemplate.Template = make([]gen.ClientConfigTemplateItem, len(source.Template))
		for i := 0; i < len(source.Template); i++ {
			apiClientConfigTemplate.Template[i] = gen.ClientConfigTemplateItem(source.Template[i])
		}
	}
	apiClientConfigTemplate.VlessEmailField = source.VlessEmailField
	apiClientConfigTemplate.VlessUUIDField = source.VlessUUIDField
	return apiClientConfigTemplate
}
