#!/bin/sh
set -e

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║               XRAYMAN DOCKER CONTAINER STARTING...                    ║"
echo "╠═══════════════════════════════════════════════════════════════════════╣"
echo "║                                                                       ║"
echo "║  * view actual help and env variables:                                ║"
echo "║    docker compose run --rm xray-node --help                           ║"
echo "║                                                                       ║"
echo "║  * create xray server and client configs in 'xray-node-config'        ║"
echo "║    (see example inside)                                               ║"
echo "║                                                                       ║"
echo "║  * start xray-node:                                                   ║"
echo "║    docker compose up -d                                               ║"
echo "║                                                                       ║"
echo "║  * restart xray-node:                                                 ║"
echo "║    docker compose down && docker compose up -d                        ║"
echo "║                                                                       ║"
echo "║  * node access key will be stored in xray-node-persistent:            ║"
echo "║    cat xray-node-persistent/access.json.                              ║"
echo "║                                                                       ║"
echo "║  * view logs:                                                         ║"
echo "║    docker compose logs -n 50 -f xray-node                             ║"
echo "║                                                                       ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

exec /usr/bin/xray-node/xray-node "$@"