// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/XRay-Addons/xrayman/node/internal/http/handlers (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=mocks . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/node/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// EditUsers mocks base method.
func (m *MockService) EditUsers(ctx context.Context, add, remove []models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUsers", ctx, add, remove)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUsers indicates an expected call of EditUsers.
func (mr *MockServiceMockRecorder) EditUsers(ctx, add, remove any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUsers", reflect.TypeOf((*MockService)(nil).EditUsers), ctx, add, remove)
}

// Start mocks base method.
func (m *MockService) Start(ctx context.Context, users []models.User) (*models.NodeProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, users)
	ret0, _ := ret[0].(*models.NodeProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), ctx, users)
}

// Status mocks base method.
func (m *MockService) Status(ctx context.Context) (*models.NodeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(*models.NodeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockServiceMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockService)(nil).Status), ctx)
}

// Stop mocks base method.
func (m *MockService) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockServiceMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockService)(nil).Stop), ctx)
}
