openapi: 3.0.3
info:
  title: XRay node API
  version: 1.0.0

paths:
  /start:
    $ref: "./paths/service.yaml#/Start"

  /stop:
    $ref: "./paths/service.yaml#/Stop"

  /status:
    $ref: "./paths/service.yaml#/Status"

  /users/edit:
    $ref: "./paths/edit.yaml#/EditUsers"

  /stats:
    $ref: "./paths/stats.yaml#/GetStats"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
