// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../pkg/api/http/gen/oas_server_gen.go
//
// Generated by this command:
//
//	mockgen -source=../../../pkg/api/http/gen/oas_server_gen.go -destination=./mocks/mock_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/XRay-Addons/xrayman/node/pkg/api/http/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// EditUsers mocks base method.
func (m *MockHandler) EditUsers(ctx context.Context, req *api.EditUsersRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUsers", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUsers indicates an expected call of EditUsers.
func (mr *MockHandlerMockRecorder) EditUsers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUsers", reflect.TypeOf((*MockHandler)(nil).EditUsers), ctx, req)
}

// GetStatus mocks base method.
func (m *MockHandler) GetStatus(ctx context.Context) (*api.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx)
	ret0, _ := ret[0].(*api.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockHandlerMockRecorder) GetStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockHandler)(nil).GetStatus), ctx)
}

// NewError mocks base method.
func (m *MockHandler) NewError(ctx context.Context, err error) *api.ErrorStatusCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewError", ctx, err)
	ret0, _ := ret[0].(*api.ErrorStatusCode)
	return ret0
}

// NewError indicates an expected call of NewError.
func (mr *MockHandlerMockRecorder) NewError(ctx, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewError", reflect.TypeOf((*MockHandler)(nil).NewError), ctx, err)
}

// Start mocks base method.
func (m *MockHandler) Start(ctx context.Context, req *api.StartRequest) (*api.StartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, req)
	ret0, _ := ret[0].(*api.StartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockHandlerMockRecorder) Start(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHandler)(nil).Start), ctx, req)
}

// Stop mocks base method.
func (m *MockHandler) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHandlerMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHandler)(nil).Stop), ctx)
}
