version: "3.8"
services:
  xrayman-db:
    image: postgres:16-alpine
    container_name: xrayman-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: xray-nodeman
      POSTGRES_DB: xrayman_db
      POSTGRES_PASSWORD: { POSTGRESS_PASSWORD }
    volumes:
      - xrayman_db_data:/var/lib/postgresql/data

  xrayman-db-backup:
    image: prodrigestivill/postgres-backup-local:16
    container_name: xrayman-db-backup
    restart: unless-stopped
    depends_on:
      - xrayman-db
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_HOST: xrayman-db
      POSTGRES_USER: xrayman_user
      POSTGRES_PASSWORD: super_secure_db_password_change_me
      POSTGRES_DB: xrayman_db
      POSTGRES_EXTRA_OPTS: "-Z6"
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7

  xrayman-nodeman:
    image: ghcr.io/xray-addons/xrayman:VERSION_PLACEHOLDER
    container_name: xray-nodeman
    restart: unless-stopped
    depends_on:
      - xrayman-db
    ports:
      - "8080:80"
    env_file:
      - xray-nodeman.env
    environment:

volumes:
  xrayman_db_data:
