// Code generated by MockGen. DO NOT EDIT.
// Source: users_service.go
//
// Generated by this command:
//
//	mockgen -source=users_service.go -destination=./mocks/mock_users_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersService is a mock of UsersService interface.
type MockUsersService struct {
	ctrl     *gomock.Controller
	recorder *MockUsersServiceMockRecorder
	isgomock struct{}
}

// MockUsersServiceMockRecorder is the mock recorder for MockUsersService.
type MockUsersServiceMockRecorder struct {
	mock *MockUsersService
}

// NewMockUsersService creates a new mock instance.
func NewMockUsersService(ctrl *gomock.Controller) *MockUsersService {
	mock := &MockUsersService{ctrl: ctrl}
	mock.recorder = &MockUsersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersService) EXPECT() *MockUsersServiceMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUsersService) DeleteUser(ctx context.Context, p models.DeleteUserParams) (*models.DeleteUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, p)
	ret0, _ := ret[0].(*models.DeleteUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersServiceMockRecorder) DeleteUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersService)(nil).DeleteUser), ctx, p)
}

// DisableUser mocks base method.
func (m *MockUsersService) DisableUser(ctx context.Context, p models.DisableUserParams) (*models.DisableUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUser", ctx, p)
	ret0, _ := ret[0].(*models.DisableUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableUser indicates an expected call of DisableUser.
func (mr *MockUsersServiceMockRecorder) DisableUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUser", reflect.TypeOf((*MockUsersService)(nil).DisableUser), ctx, p)
}

// EnableUser mocks base method.
func (m *MockUsersService) EnableUser(ctx context.Context, p models.EnableUserParams) (*models.EnableUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableUser", ctx, p)
	ret0, _ := ret[0].(*models.EnableUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableUser indicates an expected call of EnableUser.
func (mr *MockUsersServiceMockRecorder) EnableUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableUser", reflect.TypeOf((*MockUsersService)(nil).EnableUser), ctx, p)
}

// GetUser mocks base method.
func (m *MockUsersService) GetUser(ctx context.Context, p models.GetUserParams) (*models.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, p)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUsersServiceMockRecorder) GetUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUsersService)(nil).GetUser), ctx, p)
}

// ListUsers mocks base method.
func (m *MockUsersService) ListUsers(ctx context.Context, p models.ListUserParams) (*models.ListUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, p)
	ret0, _ := ret[0].(*models.ListUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUsersServiceMockRecorder) ListUsers(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUsersService)(nil).ListUsers), ctx, p)
}

// NewUser mocks base method.
func (m *MockUsersService) NewUser(ctx context.Context, p models.NewUserParams) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUser", ctx, p)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUser indicates an expected call of NewUser.
func (mr *MockUsersServiceMockRecorder) NewUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUser", reflect.TypeOf((*MockUsersService)(nil).NewUser), ctx, p)
}
