// Code generated by MockGen. DO NOT EDIT.
// Source: nodes_service.go
//
// Generated by this command:
//
//	mockgen -source=nodes_service.go -destination=./mocks/mock_nodes_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockNodesService is a mock of NodesService interface.
type MockNodesService struct {
	ctrl     *gomock.Controller
	recorder *MockNodesServiceMockRecorder
	isgomock struct{}
}

// MockNodesServiceMockRecorder is the mock recorder for MockNodesService.
type MockNodesServiceMockRecorder struct {
	mock *MockNodesService
}

// NewMockNodesService creates a new mock instance.
func NewMockNodesService(ctrl *gomock.Controller) *MockNodesService {
	mock := &MockNodesService{ctrl: ctrl}
	mock.recorder = &MockNodesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodesService) EXPECT() *MockNodesServiceMockRecorder {
	return m.recorder
}

// DeleteNode mocks base method.
func (m *MockNodesService) DeleteNode(ctx context.Context, p models.DeleteNodeParams) (*models.DeleteNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, p)
	ret0, _ := ret[0].(*models.DeleteNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockNodesServiceMockRecorder) DeleteNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockNodesService)(nil).DeleteNode), ctx, p)
}

// ListNodes mocks base method.
func (m *MockNodesService) ListNodes(ctx context.Context, p models.ListNodeParams) (*models.ListNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx, p)
	ret0, _ := ret[0].(*models.ListNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockNodesServiceMockRecorder) ListNodes(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockNodesService)(nil).ListNodes), ctx, p)
}

// NewNode mocks base method.
func (m *MockNodesService) NewNode(ctx context.Context, p models.NewNodeParams) (*models.NewNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNode", ctx, p)
	ret0, _ := ret[0].(*models.NewNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNode indicates an expected call of NewNode.
func (mr *MockNodesServiceMockRecorder) NewNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNode", reflect.TypeOf((*MockNodesService)(nil).NewNode), ctx, p)
}

// StartNode mocks base method.
func (m *MockNodesService) StartNode(ctx context.Context, p models.StartNodeParams) (*models.StartNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartNode", ctx, p)
	ret0, _ := ret[0].(*models.StartNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartNode indicates an expected call of StartNode.
func (mr *MockNodesServiceMockRecorder) StartNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNode", reflect.TypeOf((*MockNodesService)(nil).StartNode), ctx, p)
}

// StopNode mocks base method.
func (m *MockNodesService) StopNode(ctx context.Context, p models.StopNodeParams) (*models.StopNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopNode", ctx, p)
	ret0, _ := ret[0].(*models.StopNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopNode indicates an expected call of StopNode.
func (mr *MockNodesServiceMockRecorder) StopNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopNode", reflect.TypeOf((*MockNodesService)(nil).StopNode), ctx, p)
}
