// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DisableUser mocks base method.
func (m *MockService) DisableUser(ctx context.Context, p models.DisableUserParams) (*models.DisableUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableUser", ctx, p)
	ret0, _ := ret[0].(*models.DisableUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableUser indicates an expected call of DisableUser.
func (mr *MockServiceMockRecorder) DisableUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableUser", reflect.TypeOf((*MockService)(nil).DisableUser), ctx, p)
}

// EnableUser mocks base method.
func (m *MockService) EnableUser(ctx context.Context, p models.EnableUserParams) (*models.EnableUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableUser", ctx, p)
	ret0, _ := ret[0].(*models.EnableUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableUser indicates an expected call of EnableUser.
func (mr *MockServiceMockRecorder) EnableUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableUser", reflect.TypeOf((*MockService)(nil).EnableUser), ctx, p)
}

// GetUserSub mocks base method.
func (m *MockService) GetUserSub(ctx context.Context, p models.GetUserSubParams) (*models.GetUserSubResult, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSub", ctx, p)
	ret0, _ := ret[0].(*models.GetUserSubResult)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserSub indicates an expected call of GetUserSub.
func (mr *MockServiceMockRecorder) GetUserSub(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSub", reflect.TypeOf((*MockService)(nil).GetUserSub), ctx, p)
}

// ListNodes mocks base method.
func (m *MockService) ListNodes(ctx context.Context, p models.ListNodeParams) (*models.ListNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx, p)
	ret0, _ := ret[0].(*models.ListNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockServiceMockRecorder) ListNodes(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockService)(nil).ListNodes), ctx, p)
}

// ListUsers mocks base method.
func (m *MockService) ListUsers(ctx context.Context, p models.ListUserParams) (*models.ListUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, p)
	ret0, _ := ret[0].(*models.ListUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockServiceMockRecorder) ListUsers(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockService)(nil).ListUsers), ctx, p)
}

// NewNode mocks base method.
func (m *MockService) NewNode(ctx context.Context, p models.NewNodeParams) (*models.NewNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNode", ctx, p)
	ret0, _ := ret[0].(*models.NewNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNode indicates an expected call of NewNode.
func (mr *MockServiceMockRecorder) NewNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNode", reflect.TypeOf((*MockService)(nil).NewNode), ctx, p)
}

// NewUser mocks base method.
func (m *MockService) NewUser(ctx context.Context, p models.NewUserParams) (*models.NewUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUser", ctx, p)
	ret0, _ := ret[0].(*models.NewUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUser indicates an expected call of NewUser.
func (mr *MockServiceMockRecorder) NewUser(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUser", reflect.TypeOf((*MockService)(nil).NewUser), ctx, p)
}

// StartNode mocks base method.
func (m *MockService) StartNode(ctx context.Context, p models.StartNodeParams) (*models.StartNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartNode", ctx, p)
	ret0, _ := ret[0].(*models.StartNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartNode indicates an expected call of StartNode.
func (mr *MockServiceMockRecorder) StartNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNode", reflect.TypeOf((*MockService)(nil).StartNode), ctx, p)
}

// StopNode mocks base method.
func (m *MockService) StopNode(ctx context.Context, p models.StopNodeParams) (*models.StopNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopNode", ctx, p)
	ret0, _ := ret[0].(*models.StopNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopNode indicates an expected call of StopNode.
func (mr *MockServiceMockRecorder) StopNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopNode", reflect.TypeOf((*MockService)(nil).StopNode), ctx, p)
}
