// Code generated by MockGen. DO NOT EDIT.
// Source: subscr_service.go
//
// Generated by this command:
//
//	mockgen -source=subscr_service.go -destination=./mocks/mock_subscr_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscrService is a mock of SubscrService interface.
type MockSubscrService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscrServiceMockRecorder
	isgomock struct{}
}

// MockSubscrServiceMockRecorder is the mock recorder for MockSubscrService.
type MockSubscrServiceMockRecorder struct {
	mock *MockSubscrService
}

// NewMockSubscrService creates a new mock instance.
func NewMockSubscrService(ctrl *gomock.Controller) *MockSubscrService {
	mock := &MockSubscrService{ctrl: ctrl}
	mock.recorder = &MockSubscrServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscrService) EXPECT() *MockSubscrServiceMockRecorder {
	return m.recorder
}

// GetUserSub mocks base method.
func (m *MockSubscrService) GetUserSub(ctx context.Context, p models.UserSubParams) (*models.UserSubResult, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSub", ctx, p)
	ret0, _ := ret[0].(*models.UserSubResult)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserSub indicates an expected call of GetUserSub.
func (mr *MockSubscrServiceMockRecorder) GetUserSub(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSub", reflect.TypeOf((*MockSubscrService)(nil).GetUserSub), ctx, p)
}
