// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/XRay-Addons/xrayman/nodeman/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ListNodes mocks base method.
func (m *MockService) ListNodes(ctx context.Context, p models.ListNodeParams) (*models.ListNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNodes", ctx, p)
	ret0, _ := ret[0].(*models.ListNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodes indicates an expected call of ListNodes.
func (mr *MockServiceMockRecorder) ListNodes(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodes", reflect.TypeOf((*MockService)(nil).ListNodes), ctx, p)
}

// NewNode mocks base method.
func (m *MockService) NewNode(ctx context.Context, p models.NewNodeParams) (*models.NewNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNode", ctx, p)
	ret0, _ := ret[0].(*models.NewNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNode indicates an expected call of NewNode.
func (mr *MockServiceMockRecorder) NewNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNode", reflect.TypeOf((*MockService)(nil).NewNode), ctx, p)
}

// StartNode mocks base method.
func (m *MockService) StartNode(ctx context.Context, p models.StartNodeParams) (*models.StartNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartNode", ctx, p)
	ret0, _ := ret[0].(*models.StartNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartNode indicates an expected call of StartNode.
func (mr *MockServiceMockRecorder) StartNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNode", reflect.TypeOf((*MockService)(nil).StartNode), ctx, p)
}

// StopNode mocks base method.
func (m *MockService) StopNode(ctx context.Context, p models.StopNodeResult) (*models.StopNodeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopNode", ctx, p)
	ret0, _ := ret[0].(*models.StopNodeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopNode indicates an expected call of StopNode.
func (mr *MockServiceMockRecorder) StopNode(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopNode", reflect.TypeOf((*MockService)(nil).StopNode), ctx, p)
}
