// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemas

import "encoding/json"
import "fmt"

type AdminpagecfgJson struct {
	// prefix for admin page spa
	AdminPrefix string `json:"AdminPrefix" yaml:"AdminPrefix" mapstructure:"AdminPrefix"`

	// prefix for api requests
	ApiPrefix string `json:"ApiPrefix" yaml:"ApiPrefix" mapstructure:"ApiPrefix"`

	// List of allowed settings placeholders
	SettingsTags []string `json:"SettingsTags" yaml:"SettingsTags" mapstructure:"SettingsTags"`

	// prefix for user page spa
	UserPrefix string `json:"UserPrefix" yaml:"UserPrefix" mapstructure:"UserPrefix"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AdminpagecfgJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["AdminPrefix"]; raw != nil && !ok {
		return fmt.Errorf("field AdminPrefix in AdminpagecfgJson: required")
	}
	if _, ok := raw["ApiPrefix"]; raw != nil && !ok {
		return fmt.Errorf("field ApiPrefix in AdminpagecfgJson: required")
	}
	if _, ok := raw["SettingsTags"]; raw != nil && !ok {
		return fmt.Errorf("field SettingsTags in AdminpagecfgJson: required")
	}
	if _, ok := raw["UserPrefix"]; raw != nil && !ok {
		return fmt.Errorf("field UserPrefix in AdminpagecfgJson: required")
	}
	type Plain AdminpagecfgJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AdminpagecfgJson(plain)
	return nil
}
