// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemas

import "encoding/json"
import "fmt"

type UserpagecfgJson struct {
	// prefix for api requests
	ApiPrefix string `json:"ApiPrefix" yaml:"ApiPrefix" mapstructure:"ApiPrefix"`

	// application links
	AppLinks []UserpagecfgJsonAppLinksElem `json:"AppLinks" yaml:"AppLinks" mapstructure:"AppLinks"`

	// prefix for user page spa
	SupportLink string `json:"SupportLink" yaml:"SupportLink" mapstructure:"SupportLink"`

	// prefix for user page spa
	UserPrefix string `json:"UserPrefix" yaml:"UserPrefix" mapstructure:"UserPrefix"`
}

type UserpagecfgJsonAppLinksElem struct {
	// Name corresponds to the JSON schema field "Name".
	Name string `json:"Name" yaml:"Name" mapstructure:"Name"`

	// Platforms corresponds to the JSON schema field "Platforms".
	Platforms string `json:"Platforms" yaml:"Platforms" mapstructure:"Platforms"`

	// URL corresponds to the JSON schema field "URL".
	URL string `json:"URL" yaml:"URL" mapstructure:"URL"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserpagecfgJsonAppLinksElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["Name"]; raw != nil && !ok {
		return fmt.Errorf("field Name in UserpagecfgJsonAppLinksElem: required")
	}
	if _, ok := raw["Platforms"]; raw != nil && !ok {
		return fmt.Errorf("field Platforms in UserpagecfgJsonAppLinksElem: required")
	}
	if _, ok := raw["URL"]; raw != nil && !ok {
		return fmt.Errorf("field URL in UserpagecfgJsonAppLinksElem: required")
	}
	type Plain UserpagecfgJsonAppLinksElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserpagecfgJsonAppLinksElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserpagecfgJson) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ApiPrefix"]; raw != nil && !ok {
		return fmt.Errorf("field ApiPrefix in UserpagecfgJson: required")
	}
	if _, ok := raw["AppLinks"]; raw != nil && !ok {
		return fmt.Errorf("field AppLinks in UserpagecfgJson: required")
	}
	if _, ok := raw["SupportLink"]; raw != nil && !ok {
		return fmt.Errorf("field SupportLink in UserpagecfgJson: required")
	}
	if _, ok := raw["UserPrefix"]; raw != nil && !ok {
		return fmt.Errorf("field UserPrefix in UserpagecfgJson: required")
	}
	type Plain UserpagecfgJson
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserpagecfgJson(plain)
	return nil
}
