// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/XRay-Addons/xrayman/node/internal/http/router (interfaces: Handlers)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/handlers_mock.go -package=mocks . Handlers
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// EditUsers mocks base method.
func (m *MockHandlers) EditUsers(log *zap.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUsers", log)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// EditUsers indicates an expected call of EditUsers.
func (mr *MockHandlersMockRecorder) EditUsers(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUsers", reflect.TypeOf((*MockHandlers)(nil).EditUsers), log)
}

// Start mocks base method.
func (m *MockHandlers) Start(log *zap.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", log)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockHandlersMockRecorder) Start(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockHandlers)(nil).Start), log)
}

// Status mocks base method.
func (m *MockHandlers) Status(log *zap.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", log)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockHandlersMockRecorder) Status(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockHandlers)(nil).Status), log)
}

// Stop mocks base method.
func (m *MockHandlers) Stop(log *zap.Logger) http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", log)
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockHandlersMockRecorder) Stop(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockHandlers)(nil).Stop), log)
}
