/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserPageConfig {
  /**
   * prefix for api requests
   */
  ApiPrefix: string;
  /**
   * prefix for user page spa
   */
  UserPrefix: string;
  /**
   * prefix for user page spa
   */
  SupportLink: string;
  /**
   * application links
   */
  AppLinks: {
    Name: string;
    Platforms: string;
    URL: string;
  }[];
}
