name: Publish XRayMan

on:
  push:
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  release:
    env:
      VERSION: ${{ github.ref_name }}
      COMMIT: ${{ github.sha }}
      BUILD_TIME: ${{ github.event.head_commit.timestamp }}

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      # ------------------------------------------------------------ #
      #                        Setup                                 #
      # ------------------------------------------------------------ #

      - name: Eval env variables
        run: |
          echo "CLEAN_VER=${VERSION#v}" >> "$GITHUB_ENV"

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"
          cache-dependency-path: |
            backend/node/go.sum
            backend/nodeman/go.sum

      - name: Install Go Tools
        run: |
          make tools
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10.33.2

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.3.0
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      # ------------------------------------------------------------ #
      #                        XRay node                             #
      # ------------------------------------------------------------ #

      # XRay node: build amd64 and arm64 to ./build/{ARCH}/xray-node
      - name: Node Build Project
        env:
          CGO_ENABLED: 0
        run: |
          GOOS=linux GOARCH=amd64 make build_node
          GOOS=linux GOARCH=arm64 make build_node

      # XRay node: build .deb packages
      - name: Node Pack DEB Packages
        run: |
          ./packaging/xray-node/deb/build/build.sh "$CLEAN_VER" ./build arm64
          ./packaging/xray-node/deb/build/build.sh "$CLEAN_VER" ./build amd64

      # XRay node: build and publish docker image (only for tags)
      - name: Push Multi-Arch XRay-Node Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/xray-node" | tr '[:upper:]' '[:lower:]')

          # enable emulation to build arm64 on amd64
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./packaging/xray-node/docker/xray-node.dockerfile \
            -t ghcr.io/${IMAGE_NAME}:latest -t ghcr.io/${IMAGE_NAME}:${CLEAN_VER} \
            --push .

      - name: Publish XRay-Node docker compose
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./packaging/xray-nodeman/deb/build/publish.sh "$CLEAN_VER"

      # ------------------------------------------------------------ #
      #                        XRay nodeman                          #
      # ------------------------------------------------------------ #

      # XRay nodeman: build amd64 and arm64 to ./build/{ARCH}/xray-nodeman
      - name: Nodeman Build Project
        env:
          CGO_ENABLED: 0
        run: |
          GOOS=linux GOARCH=amd64 make build_nodeman
          GOOS=linux GOARCH=arm64 make build_nodeman

      # XRay nodeman: build .deb packages
      - name: Nodeman Pack DEB Packages
        run: |
          ./packaging/xray-nodeman/deb/build.sh "$CLEAN_VER" ./build arm64
          ./packaging/xray-nodeman/deb/build.sh "$CLEAN_VER" ./build amd64

      # XRay nodeman: build and publish docker image (only for tags)
      - name: Push Multi-Arch XRay-NodeMan Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/xray-nodeman" | tr '[:upper:]' '[:lower:]')

          # enable emulation to build arm64 on amd64
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./packaging/xray-nodeman/docker/xray-nodeman.dockerfile \
            -t ghcr.io/${IMAGE_NAME}:latest -t ghcr.io/${IMAGE_NAME}:${CLEAN_VER} \
            --push .

      # ------------------------------------------------------------ #
      #                        Publish all stuff                     #
      # ------------------------------------------------------------ #

      # ГЕНЕРИРУЕМ АКТУАЛЬНЫЕ DOCKER COMPOSE ФАЙЛЫ
      - name: Prepare Docker Compose Manifests
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          CLEAN_VER=$(echo '${{ github.ref_name }}' | sed 's/^v//')

          # 1. Создаем целевые папки (без этого sed упадет с ошибкой)
          mkdir -p ./dist/docker
          mkdir -p ./dist/docker/xray-nodeman
          mkdir -p ./dist/docker/xray-nodeman/all-in-one
          mkdir -p ./dist/docker/xray-nodeman/standalone
          mkdir -p ./dist/docker/xray-node

          # 2. Заменяем плейсхолдер версии на реальный тег релиза
          sed "s/VERSION_PLACEHOLDER/$CLEAN_VER/g" ./packaging/xray-nodeman/docker/all-in-one/docker-compose.yml > ./dist/docker/xray-nodeman/all-in-one/docker-compose.yml
          sed "s/VERSION_PLACEHOLDER/$CLEAN_VER/g" ./packaging/xray-nodeman/docker/standalone/docker-compose.yml > ./dist/docker/xray-nodeman/standalone/docker-compose.yml
          sed "s/VERSION_PLACEHOLDER/$CLEAN_VER/g" ./packaging/xray-node/docker/docker-compose.yml > ./dist/docker/xray-node/docker-compose.yml

          # 3. (Опционально) Скопируйте сюда дополнительные файлы конфигурации, если они есть
          cp ./packaging/xray-nodeman/docker/all-in-one/datasource.yml ./dist/docker/xray-nodeman/all-in-one/datasource.yml
          cp ./packaging/xray-nodeman/docker/all-in-one/prometheus.yml ./dist/docker/xray-nodeman/all-in-one/prometheus.yml
          cp -r ./packaging/xray-node/config ./dist/docker/xray-node/xray-node-config

          # 4. Архиривуем папки (флаг -C временно меняет директорию, чтобы внутри архива не было лишней вложенности)
          tar -czf docker-compose.xray-nodeman.all-in-one.tar.gz -C ./dist/docker/xray-nodeman/all-in-one .
          tar -czf docker-compose.xray-nodeman.standalone.tar.gz -C ./dist/docker/xray-nodeman/standalone .
          tar -czf docker-compose.xray-node.tar.gz -C ./dist/docker/xray-node .

      # ПУБЛИКУЕМ ВСЕ АССЕТЫ В РЕЛИЗ (DEB + DOCKER COMPOSE)
      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            xray-nodeman-*.deb
            xray-node-*.deb
            docker-compose.xray-nodeman.all-in-one.tar.gz
            docker-compose.xray-nodeman.standalone.tar.gz
            docker-compose.xray-node.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # СБОРКА ОДНОГО МУЛЬТИПЛАТФОРМЕННОГО ОБРАЗА XRAY-NODEMAN
      - name: Push Multi-Arch XRay-NodeMan Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/xray-nodeman" | tr '[:upper:]' '[:lower:]')

          # Включаем эмуляцию QEMU для сборки под ARM прямо на машине Intel
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./packaging/xray-nodeman/docker/xray-nodeman.dockerfile \
            -t ghcr.io/${IMAGE_NAME}:latest -t ghcr.io/${IMAGE_NAME}:${CLEAN_VER} \
            --push .

      # СБОРКА ОДНОГО МУЛЬТИПЛАТФОРМЕННОГО ОБРАЗА XRAY-NODE
      - name: Push Multi-Arch XRay-Node Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          IMAGE_NAME=$(echo "${{ github.repository_owner }}/xray-node" | tr '[:upper:]' '[:lower:]')

          # Включаем эмуляцию QEMU для сборки под ARM прямо на машине Intel
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ./packaging/xray-node/docker/xray-node.dockerfile \
            -t ghcr.io/${IMAGE_NAME}:latest -t ghcr.io/${IMAGE_NAME}:${CLEAN_VER} \
            --push .
