name: Publish XRayMan

on:
  push:
    branches: [main] # Срабатывает при пуше в основную ветку
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.2"
          cache-dependency-path: |
            backend/node/go.sum
            backend/nodeman/go.sum

      - name: Install Go Tools
        run: |
          # Устанавливаем инструменты, нужные для make gen_backend
          go install ://github.com
          go install ://github.com
          go install go.uber.org/mock/mockgen@latest
          # ВАЖНО: прокидываем путь к бинарникам в PATH этого процесса
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install Dependencies
        run: make deps

      - name: Build Project
        run: make build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xrayman-dist
          path: build/
          retention-days: 7
