name: Publish nodeman API client

on:
  push:
    tags:
      - 'v*.*.*'   # workflow on pushing tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: |
          cd nodeman/api-client
          npm install

      - name: Generate API client
        run: |
          cd nodeman/api-client
          npm run generate

      - name: Build package
        run: |
          cd nodeman/api-client
          npm run build

      - name: Publish to GitHub Packages
        run: |
          cd nodeman/api-client
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
